"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class team31_state_t(object):
    __slots__ = ["utime", "fwd_velocity", "turn_velocity", "left_velocity", "right_velocity", "yaw_delta", "encoder_yaw_delta"]

    __typenames__ = ["int64_t", "float", "float", "float", "float", "float", "float"]

    __dimensions__ = [None, None, None, None, None, None, None]

    def __init__(self):
        self.utime = 0
        self.fwd_velocity = 0.0
        self.turn_velocity = 0.0
        self.left_velocity = 0.0
        self.right_velocity = 0.0
        self.yaw_delta = 0.0
        self.encoder_yaw_delta = 0.0

    def encode(self):
        buf = BytesIO()
        buf.write(team31_state_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qffffff", self.utime, self.fwd_velocity, self.turn_velocity, self.left_velocity, self.right_velocity, self.yaw_delta, self.encoder_yaw_delta))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != team31_state_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return team31_state_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = team31_state_t()
        self.utime, self.fwd_velocity, self.turn_velocity, self.left_velocity, self.right_velocity, self.yaw_delta, self.encoder_yaw_delta = struct.unpack(">qffffff", buf.read(32))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if team31_state_t in parents: return 0
        tmphash = (0x30733105d0fe9863) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if team31_state_t._packed_fingerprint is None:
            team31_state_t._packed_fingerprint = struct.pack(">Q", team31_state_t._get_hash_recursive([]))
        return team31_state_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

